### ISSUE TITLE
Support higher-dimensional controllers

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#110]
With 2D path planning in the near future, OkapiLib will have to support closed-loop controllers with higher input dimensions than 1, and potentially different input types than `double`. One way this could be solved is by templating the parameter to `step()`. In this way, implementing classes would specify the type of their input. This also satisfies the requirement of higher-dimensional input because implementing classes could define their own input class. Existing classes would specify this template parameter as `double` so the API would remain unchanged.

**Comment by baylessj** [comment]
I like this plan with the templates, that sounds like the best solution for maintaining the current API while not forcing multi-dof controllers to be completely separate from the current controller structure. I'm assuming that multi-dof controllers would pass all of their values in as a struct, and the step function would still take in a single newReading parameter?

**Comment by Octogonapus** [comment]
Maybe a struct, maybe a class. What's important is that step would take a template parameter instead of a `double`.

**Comment by Octogonapus** [comment]
This API change can go into v3.0.3, we don't have to use it yet.
