### ISSUE TITLE
Rephrase ChassisModel method parameters

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#202]
The `ChassisModel` method parameters imply a certain coordinate layout for the robot frame. I prefer that these parameters are rephrased to refer to directions like "forward" instead of "yAxis", etc. so we are more frame-agnostic between different libraries (like Pathfinder).

**Comment by HotelCalifornia** [comment]
~~In cases like `zRotation`, it doesn't make much sense to me to rename to `upRotation`. Instead, would something like `pitch` be okay? Or is that still assuming too much about the frame of reference?~~

**Comment by HotelCalifornia** [comment]
~~alternatively, I could be misunderstanding what I'm reading~~

**Comment by HotelCalifornia** [comment]
update: I was misreading things.

real question: is using terminology like pitch/yaw/roll okay? or is that still too frame-specific?

**Comment by Octogonapus** [comment]
That's fine.
