### ISSUE TITLE
Finish odometry

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#213]
Odometry has been sitting around in a "basically done we just need to test it for reals this time" state. This is an issue so we can track it officially.

**Comment by baylessj** [comment]
What are we looking for as a test plan exactly? I'm assuming it will be comparing the robot's assumed position from the odometry versus its actual position, but with what motor/sensor setups? I currently have a test robot with 3 encoder wheels and a test robot with 2 v5 motors, will that be sufficient?

**Comment by Octogonapus** [comment]
Yes and yes. I want to see how accurate it is during controlled movements. Try to move the robots the same during all the test runs.

**Comment by 3038922** [comment]
Previous Odometry were purely encoder-based. I used Kalman filters to fuse encoder and gyro angles much better. Wheels always skid can affect accuracy. Hopefully there's a default fusion of GYRO and ENCODER to get angle information.
