### ISSUE TITLE
where is  odometry.hpp?

### ISSUE THREAD

**Issue by 3038922** [OkapiLib/OkapiLib#248]
I have used oklib for cortex for half a year.
But I can't find odometry.hpp in okapilib 3.3.4.
Is there any chassis structure for the Mecanum wheel?I can't find any joy contorl for Mecanum.
If I want to write a Mecanum class of my own,Which class should I inherit?
I have no ability to write odometry with Mecanum.
Thank you.

**Comment by Octogonapus** [comment]
There is no odometry yet. There is no chassis model for mecanums. You need to subclass `ChassisModel` if you want to make your own.
