### ISSUE TITLE
How to use C++ to design the UI program architecture? 

### ISSUE THREAD

**Issue by 3038922** [OkapiLib/OkapiLib#250]
I'm really sorry to ask questions here, because no one can answer the official BBS, I really can't find a place to ask.
![1](https://user-images.githubusercontent.com/33926386/46758504-91d23780-ccff-11e8-9c85-a703a9570364.jpg)
![2](https://user-images.githubusercontent.com/33926386/46758554-af9f9c80-ccff-11e8-84ee-66778ee71dce.jpg)
I don't know about LVGL, and I'm currently lumping all of my code into one class.
This class is long. The code is ugly.
And the system sensitivity is very low, estimated I did not release memory relationship.
I don't know how to design a destructor to free memory
Do you have good architecture design to share?

If I use shared_prt<UserDisplay>_data into another class, the v5system will report an error.
And i don't konw why....
The ugly architecture I designed...
base class
![image](https://user-images.githubusercontent.com/33926386/46758611-d8279680-ccff-11e8-80de-1a6930172fe8.png)
The constructor
![image](https://user-images.githubusercontent.com/33926386/46758632-e37ac200-ccff-11e8-937b-7deee1a854f9.png)
opcontrol.cpp
![image](https://www.vexforum.com/index.php/attachment/5bbda25a240b2_4.png)

**Comment by HotelCalifornia** [comment]
This isn't really the right place to ask about this, as it's more of a PROS 3-related issue than OkapiLib but I'll try to answer anyway.

LVGL is a C library, and provides no C++ code by default. We are working on creating a high-level C++ wrapper around LVGL, but it's not finished yet.

As for how you can write a destructor, the best way in this case would be to call `lv_obj_del` on all the objects you define that have children objects.
