### ISSUE TITLE
I hope to add a version string.

### ISSUE THREAD

**Issue by 3038922** [OkapiLib/OkapiLib#256]
Maybe I have code obsessive-compulsive disorder. ^^!
thank you.

![3](https://user-images.githubusercontent.com/33926386/47707453-cd10b800-dc66-11e8-9729-2e10707befc1.png)

**Comment by PixelDust22** [comment]
Are you saying that you're hoping to have a string constant representing the OkapiLib version number?

Like this?
#define OKAPILIB_VERSION_STRING "3.4.0"

We already have a version number defined in Makefile. To use it in the project, try something like this: https://www.linkedin.com/pulse/incrementing-version-numbers-gcc-projects-makefiles-jan-nejman/

**Comment by Octogonapus** [comment]
I'm not sure of any significant gain users would get from this. If more people want it, this can be reopened.
