### ISSUE TITLE
Arcade control in SkidSteerModel does not work with negative 0.

### ISSUE THREAD

**Issue by vexcat** [OkapiLib/OkapiLib#293]
**Describe the bug**
If you pass `(-0, -1)` to SkidSteerModel's .arcade, it'll go backwards instead of turning. (Note the negative zero, the result of `(-1 * 0.0)`). Normally, -0's don't cause issues, but the `copysign` in .arcade's definition brings it out. 
**Steps To Reproduce**
Call .arcade with (-0, -1)
**Expected behavior**
I expected the robot to turn left, but it went backwards instead
**Versions**
I am on PROS 3.1.4 and okapilib 3.3.6.
**Code to reproduce**
```
void opcontrol() {
  auto c = ChassisControllerFactory::create(
    -11, 1
  );
  pros::Controller m(pros::E_CONTROLLER_MASTER);
  while(true) {
    c.arcade(m.get_analog(ANALOG_LEFT_X)/-127.0, m.get_analog(ANALOG_LEFT_Y)/-127.0);
    pros::delay(20);
  }
}
```

**Comment by Octogonapus** [comment]
It sounds, from your example, that the joystick can return `-0` sometimes. You should use a deadband on the joysticks, `+/- 5` tends to work well.
