### ISSUE TITLE
Question About the Async Pos PID Controller

### ISSUE THREAD

**Issue by Leo428** [OkapiLib/OkapiLib#294]
### Description

I see this from the documentation:
```
static AsyncPosPIDController posPID(
  std::shared_ptr<ControllerInput<double>> iinput,
  std::shared_ptr<ControllerOutput<double>> ioutput,
  double ikP, double ikI, double ikD, double ikBias = 0,
  std::unique_ptr<Filter> iderivativeFilter = std::make_unique<PassthroughFilter>()
)
```
Now I create a controller using the Async Controller Factory and pass down a double value obtained from the vision sensor as the input and pass down a motor as the output. I am confused about how to use the std::shared_ptr<ControllerInput<double>> and the std::shared_ptr<ControllerOutput<double>>.

### Versions

kernel 3.1.2
okapilib 3.3.7

**Comment by Octogonapus** [comment]
You will need to implement `ControllerInput` for your vision sensor input. For the output, an `AbstractMotor` is already a `ControllerOutput<double>` so just make one, `std::make_shared<Motor>(MOTOR_PORT)`.
