### ISSUE TITLE
IterativePosPIDController derivative does not appear to work

### ISSUE THREAD

**Issue by evangs1** [OkapiLib/OkapiLib#298]
### Description

When controlling a robot with a PID controller using IterativePosPIDController, the proportional component of the code works, but the derivative component does not appear to do anything, even if kD is set to a ridiculously high value like 10000000.

### Steps to Reproduce

1. Create an instance of IterativePosPIDController using its factory, defining constants
2. setTarget()
3. Run the step() function and set motor speed to its output

**Expected behavior:** The robot should slow down when nearing its target value, depending on how high kD is.

**Actual behavior:** The behavior of the PID remains the same no matter the value of kD.
### Versions

PROS   3.1.4
okapilib   3.3.7
### Additional Information

code snippet from src/autonomous.cpp from [https://github.com/evangs1/99904a-pros](url)

```
//create controller instance
auto gyroTurnController = okapi::IterativeControllerFactory::posPID(0.0018, 0.0, 1000, 0, std::make_unique<okapi::AverageFilter<3>>());

   //configure motors
   okapi::Motor rf(-DRIVE_RIGHT_FRONT_PORT);
   okapi::Motor rb(-DRIVE_RIGHT_BACK_PORT);
   okapi::Motor lf(-DRIVE_LEFT_FRONT_PORT);
   okapi::Motor lb(-DRIVE_LEFT_BACK_PORT);

   //set sample time and target
   gyroTurnController.setSampleTime(10_ms);

   gyroTurnController.setTarget(400);

   //run loop
   while (!gyroTurnController.isSettled()) {
      double newInput = gyro.get();
      double newOutput = gyroTurnController.step(newInput);
      rf.move(newOutput*127);
      rb.move(newOutput*127);
      lf.move(newOutput*127);
      lb.move(newOutput*127);


      pros::delay(10);
   }

**Comment by Octogonapus** [comment]
I can confirm this is a bug introduced in 3ac748c. This will be fixed as part of v4.0.0. Thanks for the bug report.
