### ISSUE TITLE
Add common math functions to RQuantity

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#302]
The units API can be verbose to use when you need common math functions such as `sqrt()`, `sin()`, `cos()`, etc. `RQuantity` should define these.

**Comment by juliaschatz** [comment]
Are you still working on this?

**Comment by Octogonapus** [comment]
Nope, that's why it's in the freezer.

**Comment by agrsh** [comment]
If these functions are implemented, I think they should be done as free functions rather than member functions. That would allow users to write code like ``` sqrt(pt.x * pt.x + pt.y * pt.y)``` instead of ```(pt.x * pt.x + pt.y * pt.y).sqrt()```
