### ISSUE TITLE
Motion Profile Memory Permission Error

### ISSUE THREAD

**Issue by Leo428** [OkapiLib/OkapiLib#321]
**Describe the bug**
In the middle of the autonomous period, sometimes when I switched the competition switch to disable, the Brain's screen will display an error box saying "Memory Permission Error"  

**Steps To Reproduce**
Create a motion profile controller, generate a path, and run the path; then disable the bot in the middle of the period. 

**Expected behavior**
The screen should not display the memory permission error. 

**Versions**
kernel    3.1.5      pros-mainline
okapilib  3.3.8      pros-mainline

**Additional Information**
```c++
profileController.generatePath({Point{0_ft, 0_ft, 0_deg}, Point{3.8_ft, 0_ft, 0_deg}}, "A");
profileController.setTarget("A");
profileController.waitUntilSettled();
```

**Comment by Octogonapus** [comment]
This is a known bug. Unfortunately, I can't fix it until a feature in the kernel is implemented. For now, the workaround is to allocate all objects which have an internal task on the heap, i.e. `ChassisControllerPID`, `AsyncMotionProfileController`, `AsyncLinearMotionProfileController`.

**Comment by Octogonapus** [comment]
Depends on https://github.com/purduesigbots/pros/issues/86
