### ISSUE TITLE
IterativePosPIDController doesn't handle the kD gain properly.

### ISSUE THREAD

**Issue by vexcat** [OkapiLib/OkapiLib#332]
**Describe the bug**
An IterativePosPIDController will speed up as it gets closer to the target according to the kD value, not slow down as it should. This is because the IterativePosPIDController substracts the derivative term instead of adding it. The difference in error will already be negative, so this will negate a negative and make the robot move faster as it approaches the target.

**Steps To Reproduce**
1. Make a ChassisControllerPID with distance gains of [0.002, 0, 0.008].
2. The robot will not slow down as it approaches the target
3. Negate the D gain
4. The robot will slow down as it approaches the target

**Expected behavior**
I expected the derivative term to be added, slowing down the robot as it the error gets closer to 0.

**Versions**
I am on OkapiLib 3.3.9 on PROS version 3.1.5.

**Additional Information**
No additional information.

**Comment by Octogonapus** [comment]
Removing workaround available because this has to do with a non-configurable loop timing in CCPID (unless you subclass it).
