### ISSUE TITLE
Add a method to change TimeUtils arguments in the CC Factory

### ISSUE THREAD

**Issue by Heasummn** [OkapiLib/OkapiLib#339]
**Is your feature request related to a problem? Please describe.**
Currently, the Chassis Controller takes a long time between motions, I would like to tune this by changing the SettledUtils that it checks during `waitUntilSettled`, but much to my dismay, there is no way to do that through the factory. 

**Describe the solution you'd like**
A factory method, or a method in the Chassis Controller to edit and change the `TimeUtils` argument. 

**Versions**
Okapi 3.3.10 and Kernel 3.1.5

**Comment by Octogonapus** [comment]
This has been added for v4.0.0.
