### ISSUE TITLE
AMPC's removePath function can segfault if path to free is running

### ISSUE THREAD

**Issue by baylessj** [OkapiLib/OkapiLib#360]
**Describe the bug**
Calling `AsyncMotionProfileController::removePath()` to free the currently running path can cause a segmentation fault.

**Steps To Reproduce**
Set a target to the AMPC and then free the target before the path has completed.

**Expected behavior**
The controller should be disabled prior to the path's removal ideally, or the removePath function could refuse to remove the path and warn the user about the conflict.

**Versions**
PROS: 3.1.6
OkapiLib: 3.3.8

**Additional Information**
The reason I discovered this issue was because I subclassed AMPC and added a custom waitUntilSettled() implementation that allowed for exiting the movement prior to the end of the path, in case a line was detected or the vision sensor returned something useful or whatnot. In order to save space for paths I free the path soon after the path completes, and in the case of an early exit I would get a segfault when freeing the path.

**Comment by Octogonapus** [comment]
Surprise! Who could have seen this coming /s
Fine. I guess I will count this as a bug. We can add an atomic flag for when a path is running and return from `removePath()` early (log a warning and return an error code, maybe just a boolean) if the path is running.

**Comment by juliaschatz** [comment]
Instead of failing to remove the path, the more expected operation may be to stop the path running, then remove it.

**Comment by Octogonapus** [comment]
I think that if a path is running and you try to remove it, that is your mistake. Maybe we need a `stop()` method you should call first, before removing a path?

**Comment by juliaschatz** [comment]
It looks like reset() fills that niche.
