### ISSUE TITLE
Add derived telemetry methods to Motor/MotorGroup

### ISSUE THREAD

**Issue by juliaschatz** [OkapiLib/OkapiLib#364]
**Is your feature request related to a problem? Please describe.**
Determining whether a motor/group has reached its target currently requires either a wrapper class or external methods. 

**Describe the solution you'd like**
Add methods to AbstractMotor:
- double getPositionError() - difference between target position and actual position, in encoder units
- double getVelocityError() - difference between target velocity and actual velocity, in encoder units
- (possibly?) waitUntilSettled that mirrors AsyncController, which blocks until the profiled movement is finished.

**Describe alternatives you've considered**
Write a wrapper class for Motor and MotorGroup. Kind of a pain. This is really something that should be part of the API
Create the get\*Error functions for each system that requires them. This is also a pain. DRY.

**Versions**
okapilib v4.0.0
kernel  3.1.7-commit.15.40228e3

**Comment by Octogonapus** [comment]
I really want to tell you that this isn't the responsibility of `AbstractMotor`, but given that it has other methods along this vein, I guess it is.

**Comment by Octogonapus** [comment]
Your third point, `waitUntilSettled`, would require a `SettledUtil`, right? Unless there is a way to check if a profiled movement is done that I don't know about. If it does require a `SettledUtil`, then I don't want that on `AbstractMotor`.

**Comment by juliaschatz** [comment]
It would require a bit more work, that's why I left it as a maybe. Why don't you want a `SettledUtil` on `AbstractMotor`?

**Comment by Octogonapus** [comment]
I think that would cause `AbstractMotor` to have too many responsibilities. It already has too many as-is, but that's a fault of the hardware it models.
