### ISSUE TITLE
ADI Encoder on ports E and F returns PROS_ERR in v4

### ISSUE THREAD

**Issue by Heasummn** [OkapiLib/OkapiLib#372]
**Describe the bug**
ADI Encoders on ports E/F read `PROS_ERR`.

**Steps To Reproduce**
Using a Robot with an ADI Encoder in ports E and F, create an ADIEncoder instance. Calling `encoder.get()` will return `PROS_ERR` instead of the actual value of the encoder. 

My specific robot also had an encoder on ports G and H, I'm unsure if this caused the issue. Moving the encoder to ports A and B solved the issue. I'd need further testing to see if ports E and F are the issues, or if it is because of something like two encoders next to each other that is the problem. 

**Versions**
PROS 3.1.6, running the Odometry branch of Okapilib.

**Comment by juliaschatz** [comment]
(I don't have access to a v5 so I can't test myself) Does this issue occur with the PROS ADIEncoder C or C++ APIs? The Okapi ADIEncoder is a pretty thin wrapper on the PROS version.

**Comment by Octogonapus** [comment]
This issue has been fixed in feature/odometry.
