### ISSUE TITLE
Add isSettled method

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#386]
`ChassisController` should have an `isSettled()` method, implemented using the existing logic that checks `SettledUtil::isSettled()`.

**Comment by codeNinjaDev** [comment]
It would be nice to have motors have this method also.

**Comment by Octogonapus** [comment]
> It would be nice to have motors have this method also.

They basically do, through https://okapilib.github.io/OkapiLib/classokapi_1_1AbstractMotor.html#aa46c96a6eec7921ad5b12fcd4119358e
