### ISSUE TITLE
The "Arcade" and "Tank" commands are missing / can't be found

### ISSUE THREAD

**Issue by 0b101** [OkapiLib/OkapiLib#400]
**Describe the bug**
I was attempting to use Okapilib 4.0.0 today, but whenever I type in 
```
drive->arcade(controller.getAnalog(ControllerAnalog::leftY), controller.getAnalog(ControllerAnalog::rightY));
```
I get an error saying: 
```
error: 'using element_type = class okapi::ChassisController' {aka 'class okapi::ChassisController'} has no member named 'arcade' drive->arcade(controller.getAnalog(ControllerAnalog::leftY,
```

**Steps To Reproduce**
1) Start a new PROS project using the latest Okapilib built from the "feature/v4.0.0" branch (RC8) and the latest PROS kernel (3.2.0)
2) Copy and paste in the code from the "Arcade drive" section of https://github.com/OkapiLib/OkapiLib/blob/feature/v4.0.0/docs/tutorials/walkthrough/clawbot.md
3) Attempt to build using prosv5 make
4) See error

**Expected behavior**
The "arcade" command should be correctly added to the ChassisController and should be recognized.

**Versions**
```
Name      Version    Origin
--------  ---------  -------------
kernel    3.2.0      pros-mainline
okapilib  4.0.0-RC8  local

```
**Additional Information**
N/A

**Comment by Octogonapus** [comment]
This is only a problem with the tutorial. You should do `drive->getModel()` first, i.e. `drive->getModel()->arcade(...)`.
