### ISSUE TITLE
Chassis Controller Builder tutorial uses non-existing methods

### ISSUE THREAD

**Issue by nathan-moore** [OkapiLib/OkapiLib#421]
**Describe the bug**
In the "gearset and dimensions" part of the [tutorial for ChassisControllerBuilder](https://okapilib.github.io/OkapiLib/md_docs_tutorials_walkthrough_chassisControllerBuilder.html), it refers to a withDimensions function taking three arguments. Said method [does not exist.](https://okapilib.github.io/OkapiLib/classokapi_1_1ChassisControllerBuilder.html)

**Versions**
Checked on master that said overload doesn't exist.

**Comment by Octogonapus** [comment]
@nathan-moore Can you please paste the code snippet here that is giving you trouble?

**Comment by Octogonapus** [comment]
@nathan-moore Any updates on this?

**Comment by nathan-moore** [comment]
Just double checked, and it looks like we were misreading it.
