### ISSUE TITLE
Minimize turns to a maximum of 180 degrees

### ISSUE THREAD

**Issue by dcieslak19973** [OkapiLib/OkapiLib#439]
**Describe the bug**
Per: https://www.vexforum.com/t/odometry-not-turning-the-correct-way/78109 it is possible for a turn to go 270 degrees clockwise when a 90 degree counter-clockwise turn would accomplish the same thing.

**Steps To Reproduce**
RPM reproduced the behavior in the thread:

What it is doing is calculating atan of (about) -.4/-.3 which is -127 deg and then subtracting the current heading of 177 (ideally it would have been 180) from it (-127 -177) or about -304. Of course odom is using the end position from the encoders so the 0-.4 and .7-1 are the ideal number which is why the log shows -307. I guess they could optimize it by looking to see if if adding 360 or subtracting 360 would result in an smaller magnitude (or any other method). 

**Expected behavior**
Per above, "they could optimize it by looking to see if if adding 360 or subtracting 360 would result in an smaller magnitude (or any other method). "

**Versions**
Name      Version    Origin
--------  ---------  -------------
kernel    3.2.1      pros-mainline
okapilib  4.0.3      pros-mainline

**Additional Information**
Though it might make more sense to implement this at the ChassisController level

**Comment by dcieslak19973** [comment]
I wasn't able to make a branch or PR in this repo, so I created a fork and created a PR there.

**Comment by Octogonapus** [comment]
> I wasn't able to make a branch or PR in this repo

Correct, you don't have permissions to do that.

> I created a fork and created a PR there

You have made a PR from your branch `feature/issue/DJC/#439_minimize_turns` to _your_ `master`. You instead need to target your PR at _my_ `develop`. Like this:
![image](https://user-images.githubusercontent.com/4064722/77853782-f8793880-71b3-11ea-8e48-63c31362a9ed.png)
