### ISSUE TITLE
Make TurnToAngle take the shortest angle

### ISSUE THREAD

**Issue by dcieslak19973** [OkapiLib/OkapiLib#468]
**Describe the bug**
Current call uses:

`  const auto angle = iangle - odom->getState(StateMode::FRAME_TRANSFORMATION).theta;`

Which can lead to 270 degree turns instead of 90 degree turns.

Changing to:

`  const auto angle = OdomMath::constrainAngle180(iangle - odom->getState(StateMode::FRAME_TRANSFORMATION).theta);`

Should ensure the robot turns the shortest angle 

**Steps To Reproduce**

Initialize robot to a zero degree heading and ask it to TurnToAngle(-90_deg);

**Expected behavior**
Instead of turning clockwise 270 degrees, robot should turn 90 degrees counter-clockwise

**Versions**
Current

**Additional Information**
Good first issue for someone

**Comment by jazonshou** [comment]
This issue can be closed.
