### ISSUE TITLE
Add Units

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#53]
## Distance
Meter `_m` (rename Motor to `_mtr`)
Centimeter `_cm`
Millimeter `_mm`
Inch `_in`
Foot `_ft`

## Angle
Degree `_deg`
Radian `_rad`

## Speed
RPM `_rpm`
Degrees / sec `_dps`

**Comment by edjubuh** [comment]
Might not be a bad idea to create a `okapi::units` namespace... Have a single class called `Distance` with a few static methods such as `fromMeters(double meters)` `fromCentimeters(double centimeters);` that the literals are wrappers for. Also have `getMeters()`, `getInches()`, etc.

**Comment by Octogonapus** [comment]
@edjubuh Any other units you think we need? Have look in okapi/units. I am going to finish up using them wherever it's relevant.
