### ISSUE TITLE
MotorGroups with unplugged motors behave weirdly

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#55]
The MotorGroup `{-13, -14}` with motor `13` unplugged caused `moveDistance()` and `turnAngle()` to come to a "slow stop" instead of a precise stop like normal. It also did not reverse the one plugged in motor (in port `14`). Removing the unplugged motor (`13`) from the list caused the MotorGroup to behave normally.

**Comment by Octogonapus** [comment]
Looks like it's not MotorGroups specifically (it happens with Motors too). It might be the unplugged motor returning `INT32_MAX` as its position.

**Comment by Octogonapus** [comment]
The proposed solution is this:
When a motor in a group is unplugged, the group should iterate its remaining motors to find one that is plugged in, save it, and use it in the future. The default motor should be the first motor. This should be done in the constructor. If there are no motors plugged in, just return `PROS_ERR` or `PROS_ERR_F` from `getPosition`, etc.

If a chassis controller reads sensors and gets `PROS_ERR_F`, it should exit early from `moveDistance` and `turnAngle`.

**Comment by Octogonapus** [comment]
I deemed this not ready yet. I am waiting on an extra `errno` flag for unplugged ports, and the PROS team is cooking up a warning system of their own. This can wait for now.

In the meantime, users should make sure that all motors in their `MotorGroup` are plugged in.

**Comment by HotelCalifornia** [comment]
PROS warning system is included starting from kernel 3.0.7

**Comment by Octogonapus** [comment]
How does the warning system work? Does the warning show if I try to interact with a port that does not have a device attached? Is there some sort of initial configuration I can use to tell the system what ports to expect to be in use?

**Comment by HotelCalifornia** [comment]
The ports are polled and a registry of actual devices is filled (i.e. a list of the devices that are physically connected). Operations that act on devices are then validated against this registry to detect whether there is 1) an empty port ("unplugged") or 2) a different device than the operation would suggest ("mismatched")
