### ISSUE TITLE
Notes on Documentation

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#71]
## Concepts

What is a `ChassisController` and why is it important?

What’s the difference between an `Iterative` controller and an `Async` controller, and when should I use one or the other?

How can I combine sensors, filters, and controllers?

What is the purpose of `ControllerInput` and `ControllerOutput`? What classes are a type of `ControllerInput` and what classes are a type of `ControllerOutput`?

What is the factory pattern and how is it used in OkapiLib?

## Tutorials

How do I make my robot drive around in autonomous?

How do I move my lift up and down with joystick buttons?

How do I move my lift using setpoints and joystick buttons?

How do I do two things at the same time in autonomous, and how do I wait for something (like a lift moving to a target height) to complete?

**Comment by Octogonapus** [comment]
@baylessj If you wanted, you could add whatever you wrote down from our meeting last night here. This issue contains my previous thoughts on what we need in the docs department.

**Comment by baylessj** [comment]
ChassisControllers:
- ChassisControllerIntegrated is the best option for most users
- You can pass in the wheelbase dimensions if you want your movements to be in real life units

SettledUtils:
- You'll probably benefit from tuning these yourself
- Set maximums for any error related things that you don't want to check, 0 for the time

Smart pointer concept only needs discussed for more advanced users/extending okapilib, however a notice somewhere about how users will see these in headers (but won't have to worry about them) would be good

Add the reasoning behind the api/impl split in the Factories page

A timer tutorial probably ought to wait until we rework the API a decent bit

**Comment by baylessj** [comment]
ChassisModel - op control, ChassisController - auton

**Comment by Octogonapus** [comment]
What does that mean?

**Comment by baylessj** [comment]
Sorry, note to self about how to best describe the difference in application between the two. I'm thinking it probably should be added to the tutorials for chassis things.

**Comment by Octogonapus** [comment]
Could you elaborate on what you think the difference is? I'm worried that you have the wrong idea.

**Comment by baylessj** [comment]
Since ChassisModel is all openloop control and ChassisController is all closedloop, I'm assuming ChassisModel's intended for simpler, opcontrol kinds of applications and ChassisController is the opposite?

**Comment by Octogonapus** [comment]
`ChassisController` delegates to `ChassisModel`, so it has access to all of the `ChassisModel` functionality. In terms of writing simple joystick control, you are correct in thinking that's more of a `ChassisModel`-esque behavior (the relevant methods would be `tank()` and `arcade()`). But I want it to be clear that a `ChassisController` has all the methods that `ChassisModel` does.

**Comment by baylessj** [comment]
Oh, I didn't realize that. I'll be sure to specify that in its tutorial.
