### ISSUE TITLE
Controller builder

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#79]
It would be cool to have a build pattern available for controllers. Something where you can write,
```
Controller::builder()
.input(ADIUltrasonic('A', 'B'))
.filter(MedianFilter<3>())
.posPid(0, 0, 0)
.output(MotorGroup(-11, 1))
.build()
```

- `input()` would have to be first, unless there are filters or controller that could take multiple inputs
- Any number of `filter()` calls (order matters, multiple filters feed into each other)
- One "controller" call, like `posPid()` or `velPid()`
- Any number of `output()` call at the end (the controller output is sent to all outputs)

**Comment by gftabor** [comment]
Being able to support multiple inputs with simple math operations between them, or an input that is nested with multiple sensor inputs could be cool. I am thinking something simple like Left Sensor - Right Sensor.

Probably the same logic for being able to nest outputs. Simple building blocks to easily achieve something like 2 sensor wall following, or 2 sensor line following. The expected logic being

```
left Motor = straightOutput + turnOutput;
right Motor = straightOutput - turnOutput;
```
Where turnOutput was built using both input sensors and each motor controller is built with both controller outputs.

**Comment by HotelCalifornia** [comment]
would it ever be desirable to have the ability to chain controllers? alternatively, providing a method that takes a custom (composite?) controller might be nice

**Comment by Octogonapus** [comment]
I think so. There are two cases I can see:
1. "Compound" control (for lack of a better word). Two controllers that cooperate on the same level (i.e., not chained together). For example, to drive straight, one PID controller is responsible for overall distance and another is responsible for keeping straight. 
2. Cascade control. One controller feeds into another.

**Comment by HotelCalifornia** [comment]
so with respect to

> - One "controller" call, like `posPid()` or `velPid()`

what would multiple controller calls look like?
the easiest way I can think of would be something like
```cpp
Controller::builder()
.input(ADIUltrasonic('A', 'B'))
.filter(MedianFilter<3>())
.compoundControl([](...){
    return PosPID::compute(0,0,0) + VelPID::compute(0,0,0);
})
.output(MotorGroup(-11, 1))
.build()
```
or something to that effect...

<sup>yeah yeah don't shame my C++ or lack of practical control theory knowledge</sup>

**Comment by Octogonapus** [comment]
I think there would have to be a `CompoundController` class which accepts a lambda as its ctor argument. Take a look at the `IterativeController` interface, there is a decent bit it has to implement.

Do you know if a lambda can implement an interface anonymous-class-style?

**Comment by HotelCalifornia** [comment]
> Do you know if a lambda can implement an interface anonymous-class-style?

can you clarify what this means?

edit: I guess another way to do it would be to have people pass in a custom class that implements whatever interface (e.g. `IterativeController`). that way, they'd be able to fuse controllers as they like, solving the compound control issue. cascade control is another story though

**Comment by Octogonapus** [comment]
An anonymous class is a class without a name. It can be implemented "in line" meaning that you don't need to declare a class formally like you normally do. Java's lambdas are secretly anonymous classes. I want to know if C++'s lambdas can work like Java's lambdas do in this respect.

**Comment by HotelCalifornia** [comment]
right, but then what do you get out of using lambdas over an actual anonymous class? if you need inheritance, is there something wrong with doing the following ?
```cpp
[...]
.compoundController(class : public IterativeController {
   [...]
})
```
more to the point, I haven't actually been able to determine whether or not anonymous classes really exist [at least in this way] in C++ (so I guess one problem with my above snippet is that it may just be invalid altogether). it might be helpful if you could provide an example of what equivalent java code would look like, though.

**Comment by Octogonapus** [comment]
Your above snippet is not valid C++. I thought a lambda might provide an advantage in that it might be the _only_ way to have an anonymous class. I was asking because I, too, have no idea whether anonymous classes are a part of C++ or not.

**Comment by Octogonapus** [comment]
Ok, update time now that I've had some time to google things. C++ does have anonymous classes. Your snippet might be correct, I'm not sure how C++ handles having an anon class as a method argument. But either way, I think that syntax is much too verbose. An `IterativeController` has to implement, at a minimum, at least 10 methods. I think accepting a lambda and only defining the step method as the lambda body is the way to go. Then we would have to implement an `IterativeController` that accepts a lambda in its ctor and uses it to implement various methods.

**Comment by HotelCalifornia** [comment]
That's probably fine. We shouldn't close the door on allowing people to pass in a custom `IterativeController` though, in case they want some more fine-grained configuration.

Anyway, that seems to solve the compound controller case... So how would cascaded control work?

**Comment by Octogonapus** [comment]
I didn't say I was. My idea is that they can pass in a lambda, and internally we create a `CompoundController`. The user would still be able to pass in a `std::shared_ptr<IterativeController>`.

For cascaded control, I think you could call multiple controller methods like `posPid()`, `velPid()`, `compound()`.

**Comment by HotelCalifornia** [comment]
> I didn't say I was. 

I know, I was just confirming.

Chaining controller calls like that seems fine, too

**Comment by baylessj** [comment]
Is this still valid as it was originally written or is this basically an extension of the factory method currently being used? Not sure how the two would compare.

**Comment by Octogonapus** [comment]
This is still relevant. This is trying to bring in the builder pattern as a way to make controllers, rather than the factory pattern. I am still working on this issue, though it has been quiet recently.
