### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by Octogonapus** [OkapiLib/OkapiLib#8]
- [x] Add TravisCI & badge
 - [x] Add license badge
 - [x] Add downloads badge (only if conductor pulls from releases)
 - [x] Link to docs on PROS site

**Comment by HotelCalifornia** [comment]
in the installation section:

`pros conduct apply okapilib`

but you can also mention that it will be included in new projects by default

**Comment by Octogonapus** [comment]
I accept PRs :)
